
debug: false
baseUrl: http://localhost
databaseConfiguration:
  driver: mysql
  host: 127.0.0.1
  database: flarum_test
  username: root
  password: root
  prefix: ''
  port: 13306
adminUser:
  username: admin
  password: secret
  password_confirmation: secret
  email: admin@flarum.email
settings:
  forum_title: Flarum E2E