name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        ports:
          - 13306:3306



    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up skeleton
        run: |
          mkdir skeleton
          cd skeleton
          composer create-project flarum/flarum . --stability=beta
          pwd

      - name: Install and Run NGINX
        run: |
          sudo apt-get install nginx
          mv ../nginx.conf /etc/nginx/nginx.conf
          sudo systemctl start nginx
          curl http://localhost
          ls /etc/nginx
          cat /etc/nginx/nginx.conf


      - name: Create MySQL Database
        run: |
          sudo systemctl start mysql
          mysql -uroot -proot -e 'CREATE DATABASE flarum_test;' --port 13306

      - name: Cypress run
        uses: cypress-io/github-action@v1