name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        ports:
          - 13306:3306



    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up skeleton
        run: |
          sudo apt-get install composer
          mkdir skeleton
          cd skeleton
          composer create-project flarum/flarum . --stability=beta

      - name: Install and Run NGINX
        run: |
          mkdir nginx
          sudo apt-get install nginx
          sudo mv nginx.conf /etc/nginx/nginx.conf
          echo BREAKPOINT 1
          sudo systemctl start nginx
          echo BREAKPOINT 2
          sudo nginx -s reload
          echo BREAKPOINT 3
          sudo service restart nginx
          echo BREAKPOINT 4

          curl http://localhost
          cat /etc/nginx/nginx.conf


      - name: Create MySQL Database
        run: |
          sudo systemctl start mysql
          mysql -uroot -proot -e 'CREATE DATABASE flarum_test;' --port 13306

      - name: Cypress run
        uses: cypress-io/github-action@v1