name: "Cypress E2E: Installation GUI"
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        ports:
          - 13306:3306

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up skeleton
        run: |
          git clone https://github.com/flarum/flarum.git skeleton
          mv composer.json skeleton/composer.json
          cd skeleton
          composer install
          sudo chown www-data:www-data .
          sudo chown -R www-data:www-data public
          sudo chown -R www-data:www-data storage

      - name: Install and Run NGINX
        run: |
          mkdir nginx
          sudo apt-get install nginx php-fpm
          sudo service php7.4-fpm start
          sudo mv nginx.conf /etc/nginx/nginx.conf
          sudo systemctl start nginx
          sudo nginx -s reload
          sudo service nginx restart


      - name: Create MySQL Database
        run: |
          sudo systemctl start mysql
          mysql -uroot -proot -e 'CREATE DATABASE flarum_test;' --port 13306

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          config-file: cypress-install.json